// <auto-generated />
using Detetive_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Detetive_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190609015832_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Detetive_API.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Armas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cajado Devastador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Phaser"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Peixeira"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Trezoitão"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Sabre de Luz"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Bomba"
                        });
                });

            modelBuilder.Entity("Detetive_API.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Locais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Etérnia"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vulcano"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Tatooine"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Springfield"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Gotham"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Nova York"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Sibéria"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Machu Picchu"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Show do Katinguele"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "São Paulo"
                        });
                });

            modelBuilder.Entity("Detetive_API.Models.SolucaoCrime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArmaId");

                    b.Property<int>("LocalId");

                    b.Property<int>("SuspeitoId");

                    b.HasKey("Id");

                    b.ToTable("SolucaoCrimes");
                });

            modelBuilder.Entity("Detetive_API.Models.Suspeito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Suspeitos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Esqueleto"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Khan"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Dath Vader"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Sideshow Bob"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Coringa"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Duende Verde"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
